run_main_worse:
	gcc -std=gnu11 -o main_worse main_worse.c
	./main_worse

run_main_better:
	gcc -std=gnu11 -o main_better main_better.c
	./main_better

run_main_best:
	gcc -std=gnu11 -o main_best main_best.c
	./main_best

clear:
	rm -f main_worse main_better main_best