run_assertion_fault:
	gcc assertions.c -o assertions.out
	./assertions.out

run_segmentation_fault:
	gcc segfaults.c -o segfaults.out
	./segfaults.out

run_closed_pipe:
	gcc closed_pipe.c -o closed_pipe.out
	./closed_pipe.out

clear:
	rm -f assertions.out segfaults.out closed_pipe.out