write:
	gcc write.c -o write.out
	./write.out out.txt
	cat out.txt
	rm -f out.txt write.out
print:
	echo "Hello students!" > in.txt
	gcc print.c -o print.out
	./print.out in.txt
	rm -f print.out in.txt
